environments:
  - name: local
    variables:
      - name: baseUrl
        value: http://localhost:8000
      - name: authToken
        value: ""
      - name: userId
        value: ""
      - name: userEmail
        value: ""

  - name: production
    variables:
      - name: baseUrl
        value: https://api.pokedex.com
      - name: authToken
        value: ""
      - name: userId
        value: ""
      - name: userEmail
        value: ""
