name: local
variables:
  - name: baseUrl
    value: http://localhost:8000
  - name: authToken
    value: cole-seu-token-aqui
  - name: userId
    value: 00000000-0000-0000-0000-000000000000
  - name: userEmail
    value: dev@pokedex.local
