name: local
variables:
  - name: baseUrl
    value: http://localhost:8000
  - name: authToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRldkBwb2tlZGV4LmxvY2FsIiwiZXhwIjoxNzg4MDUwMTMwLCJpYXQiOjE3ODgwNDkyMzAsImp0aSI6IkV1QWszVTdCbmd0aFdYM3FlMjZ1dXciLCJzdWIiOiI3MWE1YjU5OC1kZDc0LTQzNzMtYjcyYy00M2RlZDY4YzRjNDkifQ.xNpzRmyMrIw_BRz2VxmV6fJT6BiohkM26NFzMpiZm9s
  - name: userId
    value: 71a5b598-dd74-4373-b72c-43ded68c4c49
  - name: userEmail
    value: dev@pokedex.local
